import { environment } from "../../../environments/environment.prod";

const baseUrl = environment.baseUrl;
const B2B_URL = environment.b2b_url;
const B2C_URL = environment.b2c_url;
const proj2 = "/supervision";

/* please maintain Ascending Order of the keys*/
export const apiMap = {
  addManageSMS: baseUrl + "/cms/service/AddManageSMS",
  addBankAccountDetails: baseUrl + "/cms/service/AddBankAccountDetails",
  agentBalanceManager: baseUrl + "/transaction/service/AgentBalanceManager",
  agentCreditLimitManager:
    baseUrl + "/transaction/service/AgentCreditLimitManager",
  agentList: baseUrl + "/user/service/AgentList",
  agentDetails: baseUrl + "/user/service/AgentDetails",
  agentAccoutCredit: baseUrl + "/transaction/service/AgentAccoutCredit",
  agentAccoutDebit: `${baseUrl}/transaction/service/AgentAccoutDebit`,
  apiCurrencyRateList: `${baseUrl}/cms/service/ApiCurrencyRateList`,
  addCurrencyConversion: baseUrl + "/cms/service/AddCurrencyConversion",
  deleteCurrencyConversion: `${baseUrl}/cms/service/deleteCurrencyConversion`,
  bankAccountDetails: baseUrl + "/cms/service/BankAccountDetails",
  bookingCalender: baseUrl + "/dashboard/report/travelCalendar",
  bookingDetails: baseUrl + "/transaction/service/BookingDetails",
  bookingReports: baseUrl + "/flight/service/BookingReports",
  cityList: baseUrl + "/common/service/CityList",
  currencyConverison: baseUrl + "/cms/service/CurrencyConversion",
  editUser: baseUrl + "/user/service/EditUser",
  eventNotfications: baseUrl + "/transaction/service/EventNotfications",
  flightVoucher: baseUrl + "/voucher/service/FlightVoucher",
  latestEventNotfications:
    baseUrl + "/transaction/service/LatestEventNotfications",
  loggedInUserList: baseUrl + "/user/service/LoggedInUserList",
  manageDomain: baseUrl + "/cms/service/ManageDomain",
  manageSMS: baseUrl + "/cms/service/ManageSMS",
  monthlyRecapReport: baseUrl + "/transaction/service/MonthlyRecapReport",
  passengerList: `${baseUrl}/flight/service/PassengerList`,
  processAgentBalance: baseUrl + "/transaction/service/ProcessAgentBalance",
  processAgentCreditLimit:
    baseUrl + "/transaction/service/ProcessAgentCreditLimit",
  searchHistory: baseUrl + "/transaction/service/SearchHistory",
  sEO: baseUrl + "/cms/service/SEO",
  SocialLogin: baseUrl + "/cms/service/SocialLogin",
  transactionLogs: baseUrl + "/transaction/service/TransactionLogs",
  updateApiCurrencyRate: `${baseUrl}/cms/service/UpdateApiCurrencyRate`,
  updateBankAccountDetails: baseUrl + "/cms/service/UpdateBankAccountDetails",
  updateCurrencyConverison: baseUrl + "/cms/service/UpdateCurrencyConversion",
  UpdateDomain: baseUrl + "/cms/service/UpdateDomain",
  updateManageSMS: baseUrl + "/cms/service/UpdateManageSMS",
  updateSEO: baseUrl + "/cms/service/UpdateSEO",
  UpdateSocialLogin: baseUrl + "/cms/service/UpdateSocialLogin",
  updateManageSocialLink:
    baseUrl + "/core/core-manage-social-links/updateManageSocialLink",
  updateUser: baseUrl + "/user/service/updateUser",
  userLogin: `${baseUrl}/auth/service/userLogin`,
  editProfile: `${baseUrl}/auth/service/getUserById`,
  userLogout: `${baseUrl}/auth/service/userLogout`,
  changePassword: `${baseUrl}/auth/service/changePassword`,
  forgotPassword: `${baseUrl}/auth/service/forgotPassword`,
  updatePassword: `${baseUrl}/auth/service/updatePassword`,
  resetPassword: `${baseUrl}/auth/service/resetPassword`,
  hotelTypeList: `${baseUrl}/hotel/hotel-types/hotelTypeList`,
  deleteHotelType: `${baseUrl}/hotel/hotel-types/deleteHotelType`,
  editHotelType: `${baseUrl}/hotel/hotel-types/editHotelType`,
  addHotelType: `${baseUrl}/hotel/hotel-types/addHotelType`,
  updateHotelType: `${baseUrl}/hotel/hotel-types/updateHotelType`,
  hotelAmenityList: `${baseUrl}/hotel/hotel-amenities/hotelAmenityList`,
  editHotelAmenity: `${baseUrl}/hotel/hotel-amenities/editHotelAmenity`,
  deleteHotelAmenity: `${baseUrl}/hotel/hotel-amenities/deleteHotelAmenity`,
  addHotelAmenity: `${baseUrl}/hotel/hotel-amenities/addHotelAmenity`,
  updateHotelAmenity: `${baseUrl}/hotel/hotel-amenities/updateHotelAmenity`,
  roomTypeList: `${baseUrl}/hotel/room-types/roomTypeList`,
  editRoomType: `${baseUrl}/hotel/room-types/editRoomType`,
  addRoomType: `${baseUrl}/hotel/room-types/addRoomType`,
  deleteRoomType: `${baseUrl}/hotel/room-types/deleteRoomType`,
  updateRoomType: `${baseUrl}/hotel/room-types/updateRoomType`,
  roomAmenityList: `${baseUrl}/hotel/room-amenities/roomAmenityList`,
  editRoomAmenity: `${baseUrl}/hotel/room-amenities/editRoomAmenity`,
  addRoomAmenity: `${baseUrl}/hotel/room-amenities/addRoomAmenity`,
  updateRoomAmenity: `${baseUrl}/hotel/room-amenities/updateRoomAmenity`,
  deleteRoomAmenity: `${baseUrl}/hotel/room-amenities/deleteRoomAmenity`,
  updateMeal: `${baseUrl}/master/master-meals/update`,
  addMeal: `${baseUrl}/master/master-meals/create`,
  mealList: `${baseUrl}/master/master-meals/findAll`,
  deleteMeal: `${baseUrl}/master/master-meals/delete`,

  updateTax: `${baseUrl}/master/master-tax/update`,
  addTax: `${baseUrl}/master/master-tax/create`,
  taxList: `${baseUrl}/master/master-tax/find`,
  deleteTax: `${baseUrl}/master/master-tax/delete`,

  // updateTax: `${baseUrl}/master/master-tax/update`,
  hotelChildrenPolicy: `${baseUrl}/hotel/hotels/hotelChildrenPolicy`,
  ChildrenPolicyList: `${baseUrl}/hotel/hotels/ChildrenPolicyList`,
  deleteChildrenPolicy: `${baseUrl}/hotel/hotels/deleteChildrenPolicy`,

  updateView: `${baseUrl}/master/master-views/update`,
  addView: `${baseUrl}/master/master-views/create`,
  viewList: `${baseUrl}/master/master-views/findAll`,
  deleteView: `${baseUrl}/master/master-views/delete`,

  hotelList: `${baseUrl}/hotel/hotels/hotelList`,
  searchHotels: `${baseUrl}/hotel/hotels/searchHotels`,
  hotelCount: `${baseUrl}/hotel/hotels/hotelCount`,
  addHotel: `${baseUrl}/hotel/hotels/addHotel`,
  editHotel: `${baseUrl}/hotel/hotels/editHotel`,
  updateHotel: `${baseUrl}/hotel/hotels/updateHotel`,
  deleteHotel: `${baseUrl}/hotel/hotels/deleteHotel`,
  getHotelDetail: `${baseUrl}/hotel/hotels/getHotelDetail`,
  addRoom: `${baseUrl}/hotel/hotel-rooms/addHotelRoom`,
  editRoom: `${baseUrl}/hotel/hotels/editHotelRoom`,
  // updateRoom: `${baseUrl}/hotel/hotels/updateHotelRoom`,
  updateRoom: `${baseUrl}/hotel/hotel-rooms/updateHotelRoom`,
  deleteHotelRoom: `${baseUrl}/hotel/hotel-rooms/deleteHotelRoom`,
  getRoomsByHotelId: `${baseUrl}/hotel/hotel-rooms/getRoomsByHotelId`,
  getPriceList: `${baseUrl}/hotel/room-prices/roomPriceList`,
  getRoomPrice: `${baseUrl}/hotel/room-prices/getRoomPrice`,
  deleteRoomPrice: `${baseUrl}/hotel/room-prices/deleteRoomPrice`,
  seasonList: `${baseUrl}/hotel/room-seasons/roomSeasonList`,
  addPrice: `${baseUrl}/hotel/room-prices/addRoomPrice`,
  editPrice: `${baseUrl}/hotel/room-prices/editRoomPrice`,
  updateRoomPrice: `${baseUrl}/hotel/room-prices/updateRoomPrice`,
  updatePrice: `${baseUrl}/hotel/room-seasons/updateRoomPrice`,
  priceList: `${baseUrl}/hotel/room-seasons/roomPriceList`,
  priceManagementList: `${baseUrl}/hotel/room-prices-management/priceList`,
  updatePriceManagement: `${baseUrl}/hotel/room-prices-management/updateRoomPrice`,
   roomCountUpdate: `${baseUrl}/hotel/room-prices-management/addRoomCount`,
  delRoomPrice: `${baseUrl}/hotel/room-prices-management/delRoomPrice`,
  //addSeason: `${baseUrl}/hotel/room-seasons/addRoomSeason`,
  editSeason: `${baseUrl}/hotel/room-seasons/editRoomSeason`,
  //updateSeason: `${baseUrl}/hotel/room-seasons/updateRoomSeason`,
  addSeason: `${baseUrl}/hotel/hotel-seasons/addSeason`,
  updateSeason: `${baseUrl}/hotel/hotel-seasons/updateSeason`,
  //stateList:`${baseUrl}/common/state/findAll`,
  stateList: `${baseUrl}/common/state/findAll`,
  //commonCityList: baseUrl + "/common/city/findAll",
  commonCityList: baseUrl + "/common/city/findAllCities",
  getCity: `${baseUrl}/common/city/findAll`,
  addCancellationPolicy: `${baseUrl}/hotel/room-cancellation-policies/addRoomCancellationPolicy`,
  editCancellationPolicy: `${baseUrl}/hotel/room-cancellation-policies/editRoomCancellationPolicy`,
  updateCancellationPolicy: `${baseUrl}/hotel/room-cancellation-policies/updateRoomCancellationPolicy`,
  cancellationPolicyList: `${baseUrl}/hotel/room-cancellation-policies/roomCancellationPolicyList`,
  uploadHotelLogo: `${baseUrl}/hotel/hotels/uploadHotelLogo`,
  uploadHotelImage: `${baseUrl}/hotel/hotel-images/addHotelImage`,
  supplierRequest: `${baseUrl}/user/service/supplierRequest`,
  supplierApproval: `${baseUrl}/user/service/supplierApproval`,
  supplierReject: `${baseUrl}/user/service/supplierReject`,
  addHotelImage: `${baseUrl}/hotel/hotel-images/addHotelImage`,
  hotelImageList: `${baseUrl}/hotel/hotel-images/hotelImageList`,
  deleteHotelImage: `${baseUrl}/hotel/hotel-images/deleteHotelImage`,
  primaryImage: `${baseUrl}/hotel/hotel-images/primaryImage`,
  primaryRoomImage: `${baseUrl}/hotel/room-images/primaryImage`,
  uploadRoomLogo: `${baseUrl}/hotel/room-images/addRoomImage`,
  getRoomList: `${baseUrl}/hotel/room-images/list`,
  deleteRoomList: `${baseUrl}/hotel/room-images/delete`,
  hotelSeasonList: `${baseUrl}/hotel/hotel-seasons/seasonList`,
  deleteSeason: `${baseUrl}/hotel/hotel-seasons/deleteSeason`,
  uploadHotelRoomImage: `${baseUrl}/hotel/room-images/addRoomImage`,
  masterLog: `${baseUrl}/master/master-transaction/masterLog`,
  balanceReqList: `${baseUrl}/master/master-transaction/balanceReqList`,
  creditLimitReqList: `${baseUrl}/master/master-transaction/creditLimitReqList`,
  addB2cMarkup: `${baseUrl}/core/core-markup/addB2cMarkup`,
  b2cMarkupList: `${baseUrl}/core/core-markup/b2cMarkupList`,
  preferredAirlines: `${baseUrl}/flight/flight-service/preferredAirlines`,
  b2cSupplierList: `${baseUrl}/common/supplierList`,
  b2bMarkupList: `${baseUrl}/core/core-markup/b2bMarkupList`,
  addB2bMarkup: `${baseUrl}/core/core-markup/addB2bMarkup`,
  updateFlightMarkup: `${baseUrl}/core/core-markup/updateMarkupList`,
  addBankAccountDetail: `${baseUrl}/cms/cms-bankaccounts/addBankAccountDetail`,
  listBankAccount: `${baseUrl}/cms/cms-bankaccounts/listBankAccount`,
  updateBankAccountContent: `${baseUrl}/cms/cms-bankaccounts/updateBankAccountContent`,
  updateBankImage: `${baseUrl}/cms/cms-bankaccounts/updateBankImage`,
  userList: `${baseUrl}/user/service/UserList`,
  creditBalanceDirect: `${baseUrl}/master/master-transaction/creditBalanceDirect`,
  debitBalanceDirect: `${baseUrl}/master/master-transaction/debitBalanceDirect`,
  updateBalanceRequest: `${baseUrl}/master/master-transaction/updateBalanceRequest`,
  updateCreditLimit: `${baseUrl}/master/master-transaction/updateCreditLimit`,
  updateMarkupList: `${baseUrl}/core/core-markup/updateMarkupList`,
  addB2bCommission: `${baseUrl}/core/core-commission/addB2bCommission`,
  addGdsCommission: `${baseUrl}/core/core-commission/addGdsCommission`,
  b2bCommissionList: `${baseUrl}/core/core-commission/b2bCommissionList`,
  markUpList: `${baseUrl}/core/core-markup/markupList`,
  gdsCommissionList: `${baseUrl}/core/core-commission/gdsCommissionList`,
  deleteB2bCommission: `${baseUrl}/core/core-commission/deleteB2bCommission`,
  deleteMarkup: `${baseUrl}/core/core-markup/deleteMarkup`,
  deleteGdsCommission: `${baseUrl}/core/core-commission/deleteGdsCommission`,
  updateB2bCommission: `${baseUrl}/core/core-commission/updateB2bCommission`,
  commissionList: `${baseUrl}/core/core-commission/commissionList`,
  b2bCarReport: `${baseUrl}/dashboard/report/agentCarReport`,
  b2bFlightVoucher: `${baseUrl}/dashboard/report/flightVoucher`,
  b2bHotelVoucher: `${baseUrl}/dashboard/report/hotelVoucher`,
  b2bCarVoucher: `${baseUrl}/dashboard/report/carVoucher`,
  refreshToken: `${baseUrl}/auth/service/refreshToken`,
  bookingCount: `${baseUrl}/dashboard/report/bookingCount`,
  monthWiseBookingCount: `${baseUrl}/dashboard/report/monthWiseBookingCount`,
  latestMembers: `${baseUrl}/dashboard/report/latestMembers`,
  latestTransactions: `${baseUrl}/dashboard/report/latestTransactions`,
  deleteFlightGroupBooking: `${baseUrl}/flight/group-bookings/deleteFlightGroupBooking`,
  updateFlightGroupBookingStatus: `${baseUrl}/flight/group-bookings/updateFlightGroupBookingStatus`,
  deleteHotelGroupBooking: `${baseUrl}/hotel/group-bookings/deleteHotelGroupBooking`,
  updateHotelGroupBookingStatus: `${baseUrl}/hotel/group-bookings/updateHotelGroupBookingStatus`,
  importPnrList: `${baseUrl}/webservice/flight/importPNR`,
  domainLogo: `${baseUrl}/cms/service/uploadDomainLogo`,
  paymmentGateway: `${baseUrl}/ws-apis/getWsPaymentGateWays`, // get payment gateway
  paymmentGatewayRequest: `${baseUrl}/ws-apis/updateWsPaymentGateWays`, // update payment gateway request
  updateAirlineList: `${baseUrl}/ws-apis/updateWsBlockAirline`, // update block airline list
  b2cHotelReport: `${baseUrl}/dashboard/report/b2cHotelReport`,
  b2cFlightReport: `${baseUrl}/dashboard/report/b2cFlightReport`,
  b2cCarReport: `${baseUrl}/dashboard/report/b2cCarReport`,
  b2cHotelVoucher: `${baseUrl}/dashboard/report/hotelVoucher`,
  b2cCabVoucher: `${baseUrl}/dashboard/report/carVoucher`,
  b2cFlightVoucher: `${baseUrl}/dashboard/report/flightVoucher`,
  b2cCarVoucher: `${baseUrl}/dashboard/report/carVoucher`,
  coreHelpdeskList: `${baseUrl}/core/core-helpdesks/coreHelpdeskList`,
  coreRewardList: `${baseUrl}/core/core-rewards/coreRewardList`,
  coreRewardConversion: `${baseUrl}/core/core-reward-conversion/coreRewardConversion`,
  b2cUsersList: `${baseUrl}/user/service/userList`,
  supplierList: `${B2C_URL}/webservice/supplier/find_all`,
  propertyList: `${B2C_URL}/webservice/supplier/find_properties`,
  userTypeList: `${baseUrl}/user/service/UserTypeList`,
  userTitleList: `${baseUrl}/user/service/userTitleList`,
  phoneCodeList: `${baseUrl}/dashboard/report/phoneCodeList`,
  addUser: `${baseUrl}/user/service/addUser`,
  deleteUser: `${baseUrl}/user/service/deleteUser`,
  updateUserStatus: `${baseUrl}/user/service/updateUserStatus`,
  countryList: `${baseUrl}/common/CountryList`,
  updateProfile: `${baseUrl}/user/service/updateProfile`,
  uploadUserProfilePhoto: `${baseUrl}/user/service/uploadUserProfilePhoto`,
  getUserById: `${baseUrl}/user/service/getUserById`,
  listPromocode: `${baseUrl}/core/core-promocodes/listPromocode`,
  addPromocode: `${baseUrl}/core/core-promocodes/addPromocode`,
  deletePromocode: `${baseUrl}/core/core-promocodes/deletePromocode`,
  updatePromocode: `${baseUrl}/core/core-promocodes/updatePromocode`,
  uploadPromoImage: `${baseUrl}/core/core-promocodes/uploadPromoImage`,
  emailSubscriptionsList: `${baseUrl}/core/core-subscribed-emails/emailSubscriptionsList`,
  corePaymentChargeList: `${baseUrl}/core/core-payment-charges/corePaymentChargeList`,
  updatePaymentCharge: `${baseUrl}/core/core-payment-charges/updatePaymentCharge`,
  getAllHotelGroupBooking: `${baseUrl}/hotel/group-bookings/getAllHotelGroupBooking`,
  getAllCarGroupBooings: `${baseUrl}/car/group-bookings/getAllCarGroupBooings`,
  getAllFlightGroupBookings: `${baseUrl}/flight/group-bookings/getAllFlightGroupBookings`,
  listFlightTopDestination: `${baseUrl}/flight/flight-top-destinations/listFlightTopDestination`,
  addFlightTopDestination: `${baseUrl}/flight/flight-top-destinations/addFlightTopDestination`,
  uploadFlightTopDestinationImage: `${baseUrl}/flight/flight-top-destinations/uploadFlightTopDestinationImage`,
  updateFlightTopDestination: `${baseUrl}/flight/flight-top-destinations/updateFlightTopDestination`,
  deleteFlightTopDestinationImage: `${baseUrl}/flight/flight-top-destinations/deleteFlightTopDestinationImage`,
  updateFlightTopDestinationStatus: `${baseUrl}/flight/flight-top-destinations/updateFlightTopDestinationStatus`,
  cabinClass: `${B2C_URL}/webservice/flight/cabinClassList`,
  flightAutocomplete: `${B2C_URL}/webservice/flight/autocomplete`,
  //Hotel top destinations
  listHotelTopDestination: `${baseUrl}/hotel/hotel-top-destinations/listHotelTopDestination`,
  addHotelTopDestination: `${baseUrl}/hotel/hotel-top-destinations/addHotelTopDestination`,
  uploadHotelTopDestinationImage: `${baseUrl}/hotel/hotel-top-destinations/uploadHotelTopDestinationImage`,
  updateHotelTopDestination: `${baseUrl}/hotel/hotel-top-destinations/updateHotelTopDestination`,
  deleteHotelTopDestination: `${baseUrl}/hotel/hotel-top-destinations/deleteHotelTopDestination`,
  updateHotelTopDestinationStatus: `${baseUrl}/hotel/hotel-top-destinations/updateHotelTopDestinationStatus`,
  hotelAutocompleteCity: `${B2C_URL}/webservice/hotel/hotel/autoCompleteSmyrooms`,
  hotelAutoCity: `${B2C_URL}/webservice/hotel/hotel/autoComplete`,
  //Testimonials
  addTestimonialContent: `${baseUrl}/core/core-static-page-content/addTestimonialContent`,
  updatTestimonialContent: `${baseUrl}/core/core-static-page-content/updatTestimonialContent`,
  deleteTestimonialContent: `${baseUrl}/core/core-static-page-content/deleteTestimonialContentRecords`,
  updateTestimonialContentStatus: `${baseUrl}/core/core-static-page-content/updateTestimonialContentStatus`,
  coreTestimonialContentList: `${baseUrl}/core/core-static-page-content/coreTestimonialContentList`,
  // Discounts/offers
  addDiscountContent: `${baseUrl}/core/core-static-page-content/addDiscountContent`,
  updateDiscountContent: `${baseUrl}/core/core-static-page-content/updateDiscountContent`,
  deleteDiscountContentRecords: `${baseUrl}/core/core-static-page-content/deleteDiscountContentRecords`,
  updateDiscountContentStatus: `${baseUrl}/core/core-static-page-content/updateDiscountContentStatus`,
  coreDiscountContentList: `${baseUrl}/core/core-static-page-content/coreDiscountContentList`,
  getBackAccountDetails: `${baseUrl}/core/core-static-page-content/coreDiscountContentList`,
  b2bHotelReport: `${baseUrl}/dashboard/report/agentHotelReport`,
  b2bFlightReport: `${baseUrl}/dashboard/report/agentFlightReport`,
  getAgentLoginAlert: `${baseUrl}/core/core-agent-login-alert/getAgentLoginAlert`,
  addAgentLoginAlert: `${baseUrl}/core/core-agent-login-alert/addAgentLoginAlert`,
  updateAgentLoginAlert: `${baseUrl}/core/core-agent-login-alert/updateAgentLoginAlert`,
  addStaticPageContent: `${baseUrl}/core/core-static-page-content/addStaticPageContent`,
  updateStaticPageContent: `${baseUrl}/core/core-static-page-content/updateStaticPageContent`,
  staticPageContentList: `${baseUrl}/core/core-static-page-content/staticPageContentList`,
  deleteStaticPageContent: `${baseUrl}/core/core-static-page-content/deleteStaticPageContent`,
  sliderSettingsList: `${baseUrl}/core/core-slider-settings/sliderSettingsList`,
  deleteCoreSliderSettings: `${baseUrl}/core/core-slider-settings/deleteCoreSliderSettings`,
  updatCoreSliderSettingStatus: `${baseUrl}/core/core-slider-settings/updatCoreSliderSettingStatus`,
  addSliderSetting: `${baseUrl}/core/core-slider-settings/addSliderSetting`,
  updateCoreSliderSettings: `${baseUrl}/core/core-slider-settings/updateCoreSliderSettings`,
  getModuleTypes: `${B2B_URL}/b2b/common/getModuleTypes`,
  updatCoreStaticPageContentStatus: `${baseUrl}/core/core-static-page-content/updatCoreStaticPageContentStatus`,
  coreHelpdeskAgentName: `${baseUrl}/core/core-helpdesks/coreHelpdeskAgentName`,
  uploadImage: `${baseUrl}/core/core-main-banner-images/uploadImage`,
  mainBannerImagesList: `${baseUrl}/core/core-main-banner-images/mainBannerImagesList`,
  deleteMainBannerImage: `${baseUrl}/core/core-main-banner-images/deleteMainBannerImage`,
  updateMainBannerImage: `${baseUrl}/core/core-main-banner-images/updateMainBannerImage`,
  socialNetwork: `${baseUrl}/core/core-manage-social-links/listManageSocialLink`,
  getPrivilegePageList: `${baseUrl}/core/core-static-page-content/getPrivilegePageList`,
  setUserPrivilege: `${baseUrl}/core/core-static-page-content/setUserPrivilege`,
  getPrivilegedUser: `${baseUrl}/core/core-static-page-content/getPrivilegedUser`,
  revokeParticularPrivilege: `${baseUrl}/core/core-static-page-content/revokeParticularPrivilege`,
  //Added by Asha - Manage API
  manageApiList: `${baseUrl}/ws-apis/getWsApisByModule`,
  hotelManageApiList: `${baseUrl}/cms/service/manageApi`,
  updateHotelManageApiList: `${baseUrl}/cms/service/updateApiStatus`,
  manageFlightApiList: `${baseUrl}/flight/flight-service/preferredAirlines`,
  updateApiStatus: `${baseUrl}/cms/service/updateApiStatus`,
  pnrRetrieve: `${B2C_URL}/webservice/flight/pnrRetrieve`,
  checkWalletBalance: `${B2B_URL}/b2b/account-system/checkWalletBalance`,
  deductFromWallet: `${B2B_URL}/b2b/account-system/deductFromWallet`,
  sendToAllSubscribers: `${B2B_URL}/b2b/common/sendToAllSubscribers`,
  addAirlineHotelPartnerImage: `${baseUrl}/core/core-airline-hotel-partners/addAirlineHotelPartnerImage`,
  deleteAirlineHotelPartnerImage: `${baseUrl}/core/core-airline-hotel-partners/deleteAirlineHotelPartnerImage`,
  updateAirlineHotelPartnerStatus: `${baseUrl}/core/core-airline-hotel-partners/updateAirlineHotelPartnerStatus`,
  airlineHotelPartnerList: `${baseUrl}/core/core-airline-hotel-partners/airlineHotelPartnerList`,
  updateAirlineHotelPartnerContent: `${baseUrl}/core/core-airline-hotel-partners/updateAirlineHotelPartnerContent`,
  cancelFlightBooking: `${B2C_URL}/webservice/flight/cancellation`,
  voidFlightBooking: `${B2C_URL}/webservice/flight/void`,
  importPnr: `${B2C_URL}/webservice/flight/importPNR`,
  //Update last ticketing time api's
  updateLastTicketingTime: `${baseUrl}/flight/flight-service/updateLastTicketingTime`,
  getLastTicketingUpdatedTime: `${baseUrl}/flight/flight-service/getAirLineList`,
  updateCreditLimitDirect: `${baseUrl}/master/master-transaction/updateCreditLimitDirect`,
  deductCreditLimitDirect: `${baseUrl}/master/master-transaction/deductCreditLimitDirect`,
  directImportPNR: `${B2C_URL}/webservice/flight/directImportPNR`,
  directSaveImportPNR: `${B2C_URL}/webservice/flight/directSaveImportPNR`,
  createAppReference: `${B2C_URL}/webservice/common/createAppReference`,
  // countryList: baseUrl + '/common/service/CountryList',
  // latestMembers: baseUrl + '/user/service/LatestMembers',
  // latestTransactions: baseUrl + '/transaction/service/LatestTransactions',
  // latestEventNotfications: `${baseUrl + proj2}/transaction/service/LatestEventNotfications`,
  // moduleBookingCount: baseUrl + '/transaction/service/ModuleBookingCount',
  // socialNetwork: baseUrl + '/cms/service/SocialNetwork',
  // updateProfile: `${baseUrl}/auth/service/updateUser`,
  // countryList: `${baseUrl}/common/CountryList`,
  // updateMarkupList:`${baseUrl}/core/core-markup/updateMarkupList`
  //Master -> Continent
  getMasterContinet: `${baseUrl}/common/continentList`,
  addMasterContinent: `${baseUrl}/common/addContinent`,
  updateMasterContinent: `${baseUrl}/common/updateContinent`,
  deleteMasterContinent: `${baseUrl}/common/deleteContinent`,
  getMasterCountryById: `${baseUrl}/common/getMasterCountryListbyid/:id`,
  statusChangeMasterContinent: `${baseUrl}/common/continentList`,
  getMasterState: `${baseUrl}/common/MasterStateList`,
  getMasterStateListbyid: `${baseUrl}/common/getMasterStateListbyid/:id`,
  addMasterState: `${baseUrl}/common/addMasterState`,
  updateMasterState: `${baseUrl}/common/updateMasterState`,
  deleteMasterState: `${baseUrl}/common/deleteMasterState`,
  //TourCRS -> Continent
  getTourContinet: `${baseUrl}/tour/tourContinent/tourContinentList`,
  addTourContinent: `${baseUrl}/tour/tourContinent/addTourContinent`,
  updateTourContinent: `${baseUrl}/tour/tourContinent/editTourContinent`,
  deleteTourContinent: `${baseUrl}/tour/tourContinent/deleteTourContinent`,
  statusChangeTourContinent: `${baseUrl}/tour/tourContinent/statusChangeTourContinent`,
  // Master -> Country
  getMasterCountryList: `${baseUrl}/common/countryMasterList`,
  addMasterCountry: `${baseUrl}/common/addMasterCountry`,
  editMasterCountry: `${baseUrl}/common/updateMasterCountry`,
  statusChangeMasterCountry: `${baseUrl}/common/countryMasterList`,
  deleteMasterCountry: `${baseUrl}/common/deleteMasterCountry`,
  // Master -> City
  getMasterCityList: `${baseUrl}/common/MasterCityList`,
  addMasterCity: `${baseUrl}/common/addMasterCity`,
  editMasterCity: `${baseUrl}/common/updateMasterCity`,
  getMasterCityById: `${baseUrl}/common/getMasterCityListbyid/:id`,
  // statusChangeMasterCountry: `${baseUrl}/common/countryMasterList`,
  deleteMasterCity: `${baseUrl}/common/deleteMasterCity`,

  //TourCRS -> Country
  getTourCountryList: `${baseUrl}/tour/tourCountry/tourCountryList`,
  addTourCountry: `${baseUrl}/tour/tourCountry/addTourCountry`,
  addGallery: `${baseUrl}/core/core-static-page-content/addSuperVisionGalleryRecord`,
  getGalleryList: `${baseUrl}/core/core-static-page-content/superVisionGalleryRecordList`,
  updateGalleryList: `${baseUrl}/core/core-static-page-content/updateSuperVisionGalleryRecord`,
  deleteGalleryList: `${baseUrl}/core/core-static-page-content/deleteSuperVisionGalleryRecord`,
  editTourCountry: `${baseUrl}/tour/tourCountry/editTourCountry`,
  statusChangeTourCountry: `${baseUrl}/tour/tourCountry/statusChangeTourCountry`,
  deleteTourCountry: `${baseUrl}/tour/tourCountry/deleteTourCountry`,

  //TourCRS -> City
  getTourCityList: `${baseUrl}/tour/tourCity/tourCityList`,
  addTourCity: `${baseUrl}/tour/tourCity/addTourCity`,
  editTourCity: `${baseUrl}/tour/tourCity/editTourCity`,
  deleteTourCity: `${baseUrl}/tour/tourCity/deleteTourCity`,

  //TourCRS -> Acivity
  getTourActivityList: `${baseUrl}/tour/tourActivity/tourActivityList`,
  addTourActivity: `${baseUrl}/tour/tourActivity/addTourActivity`,
  editTourActivity: `${baseUrl}/tour/tourActivity/editTourActivity`,
  statusChangeTourActivity: `${baseUrl}/tour/tourActivity/statusChangeTourActivity`,
  deleteTourActivity: `${baseUrl}/tour/tourActivity/deleteTourActivity`,

  // TourCRS -> Theme Type
  getTourThemeList: `${baseUrl}/tour/tourTheme/tourThemeList`,
  addTourTheme: `${baseUrl}/tour/tourTheme/addTourTheme`,
  editTourTheme: `${baseUrl}/tour/tourTheme/editTourTheme`,
  statusChangeTourTheme: `${baseUrl}/tour/tourTheme/statusChangeTourTheme`,
  deleteTourTheme: `${baseUrl}/tour/tourTheme/deleteTourTheme`,

  // Tour CRS -> Tour List
  getToursList: `${baseUrl}/tour/tours/toursList`,
  addTour: `${baseUrl}/tour/tours/addTour`,
  getDepartureDateList: `${baseUrl}/tour/tours/getDepartureDateList`,
  addDepartureDateList: `${baseUrl}/tour/tours/addDepartureDateList`,
  deleteDepartureDateList: `${baseUrl}/tour/tours/deleteDepartureDateList`,
  countryListByContinentId: `${baseUrl}/tour/tours/countryListByContinentId`,
  cityListByCountryId: `${baseUrl}/tour/tours/cityListByCountryId`,
  getTourVisitedCityList: `${baseUrl}/tour/tours/getTourVisitedCityList`,
  addTourVisitedCities: `${baseUrl}/tour/tours/addTourVisitedCities`,
  updateTourVisitedCities: `${baseUrl}/tour/tours/updateTourVisitedCities`,
  deleteTourVisitedCities: `${baseUrl}/tour/tours/deleteTourVisitedCities`,
  getTourVisitedCities: `${baseUrl}/tour/tours/getTourVisitedCities`,
  getTourItineraryPageData: `${baseUrl}/tour/tours/getTourItineraryPageData`,
  addTourItinerary: `${baseUrl}/tour/tours/addTourItinerary`,
  addTourDescription: `${baseUrl}/tour/tours/addTourDescription`,
  getToursPriceManagement: `${baseUrl}/tour/tours/getToursPriceManagement`,
  addToursPriceManagement: `${baseUrl}/tour/tours/addToursPriceManagement`,
  updateToursPriceManagement: `${baseUrl}/tour/tours/updateToursPriceManagement`,
  deleteToursPriceManagement: `${baseUrl}/tour/tours/deleteToursPriceManagement`,
  addImage: `${baseUrl}/tour/tours/addImage`,
  deleteTour: `${baseUrl}/tour/tours/deleteTour`,
  uploadBannerImage: `${baseUrl}/tour/tours/uploadBannerImage`,
  uploadGallery: `${baseUrl}/tour/tours/uploadGallery`,
  toursImageList: `${baseUrl}/tour/tours/toursImageList`,
  getToursById: `${baseUrl}/tour/tours/getToursById`,
  getBannerImage: `${baseUrl}/tour/tours/getBannerImage`,
  getGalleryImages: `${baseUrl}/tour/tours/getGalleryImages`,
  getBroucher: `${baseUrl}/tour/tours/getBroucher`,
  updateTour: `${baseUrl}/tour/tours/updateTour`,
  updateTourPublishStatus: `${baseUrl}/tour/tours/updateTourPublishStatus`,
  updateTourItinerary: `${baseUrl}/tour/tours/updateTourItinerary`,
  getTourItinerary: `${baseUrl}/tour/tours/getTourItinerary`,
  deleteTourImage: `${baseUrl}/tour/tours/deleteTourImage`,
  // b2cTourEnquiryList:`${baseUrl}/dashboard/report/b2cTourEnquiryList`,
  b2cTourEnquiryStatusChange: `${baseUrl}/dashboard/report/b2cTourEnquiryStatusChange`,
  cityLists: `${B2C_URL}/webservice/hotel/hotel/autoCompleteSmyrooms`,
  whyChooseUsRecordList: `${baseUrl}/core/core-static-page-content/whyChooseUsRecordList`,
  whyChooseUsAdd: `${baseUrl}/core/core-static-page-content/addWhyChooseUsRecord`,
  whyChooseUsUpdate: `${baseUrl}/core/core-static-page-content/updateWhyChooseUsRecord`,
  whyChooseUsDelete: `${baseUrl}/core/core-static-page-content/deleteWhyChooseUsRecord`,
  getTouristList: `${baseUrl}/core/core-static-page-content/touristAttractionRecordList`,
  addTouristList: `${baseUrl}/core/core-static-page-content/addTouristAttractionRecord`,
  updateTouristList: `${baseUrl}/core/core-static-page-content/updateTouristAttractionRecord`,
  deleteTouristList: `${baseUrl}/core/core-static-page-content/deleteTouristAttractionRecord`,
  addBestTimeToTravelList: `${baseUrl}/core/core-static-page-content/addBestTimeToTravelRecord`,
  updateBestTimeToTravelList: `${baseUrl}/core/core-static-page-content/updateBestTimeToTravelRecord`,
  deleteBestTimeToTravelList: `${baseUrl}/core/core-static-page-content/deleteBestTimeToTravelRecord`,
  getBestTimeToTravelList: `${baseUrl}/core/core-static-page-content/bestTimeToTravelRecordList`,
  addWhyChooseUs: `${baseUrl}/common/addwhyChooseusData`,
  whyChooseUs: `${baseUrl}/common/whyChooseusDatalist`,
  b2cTourReportList: `${baseUrl}/dashboard/report/b2cTourReport`,
  b2cTourEnquiryList: `${baseUrl}/dashboard/report/tourInquiryReport`,
  tourVoucher: `${baseUrl}/dashboard/report/tourVoucher`,
  b2bTourReportList: `${B2B_URL}/b2b/reports/tourReport`,
  b2bTourReport: `${baseUrl}/dashboard/report/b2bTourReport`,
  b2bTourEnquiryList: `${B2B_URL}/b2b/reports/tourInquiryReport`,
  b2bTourVoucher: `${B2C_URL}/webservice/tour/Voucher`,
  cancelTour: `${B2C_URL}/webservice/tour/cancelBooking`,
  //contact-Us
  ContactList: `${baseUrl}/common/ContactList`,

  //PropertyList
  findProperties: `${B2C_URL}/webservice/supplier/find_properties`,

  supplierCityList: `${B2C_URL}/webservice/common/city/findAll`,
  updateSupplier: `${B2C_URL}/webservice/supplier/update`,
  hotelCurrencyConverison: `${baseUrl}/cms/service/CurrencyConversion`,
  addIncludeMaster: `${baseUrl}/tour/includes_master/AddIncludesMasterList`,
  getPackageIncludeList: `${baseUrl}/tour/includes_master/IncludeMasterList`,
  updateIncludeMasterStatus: `${baseUrl}/tour/includes_master/UpdateMasterStatus`,
  updateIncludeMaster: `${baseUrl}/tour/includes_master/UpdateIncludeMasterList`,
  deleteIncludeMaster: `${baseUrl}/tour/includes_master/DeleteIncludeMasterList`,
  uploadIncludeMasterLogo: `${baseUrl}/common/uploadImage`,
  cityAutocomplete: `${B2C_URL}/webservice/tour/autoComplete`,
  addCityPacakageMaster: `${baseUrl}/tour/PackageMasterList/AddPackageMasterList`,
  PackageMasterList: `${baseUrl}/tour/PackageMasterList/PackageMasterList`,
  updatePackageMasterStatus: `${baseUrl}/tour/PackageMasterList/UpdatePackageMasterStatus`,
  deletePackageMasterList: `${baseUrl}/tour/PackageMasterList/DeletePackageMasterList`,
  getPackageMasterDetailsById: `${baseUrl}/tour/PackageMasterList/GetPackageMasterDetailsById`,
  updatePackageMasterList: `${baseUrl}/tour/PackageMasterList/UpdatePackageMasterList`,
  updateSupplierList: `${baseUrl}user/service/supplier/updateSupplier`,
  mailCredentials: `${baseUrl}/user/service/supplier/mailCredentials`,
  crateSupplier: `${baseUrl}/user/service/addSupplier`,
  updateSuppliers: `${baseUrl}/user/service/supplier/updateSupplier`,
  UpdateAllCurrencyConversion: `${baseUrl}/cms/service/UpdateAllCurrencyConversion`,
  updateAgentGroupStatus: `${baseUrl}/user/service/updateAgentGroup`,
  //Partner FAQ
  AddFaq: `${baseUrl}/common/AddFaq`,
  UpdateFaq: `${baseUrl}/common/UpdateFaq`,
  ListFaq: `${baseUrl}/common/ListFaq`,
  DeleteFaq: `${baseUrl}/common/DeleteFaq`,

  //Customer Faq
  AddCustomerFaq: `${baseUrl}/common/AddCustomerFaq`,
  // UpdateFaq:`${baseUrl}/common/UpdateFaq`,
  ListCustomerFaq: `${baseUrl}/common/ListCustomerFaq`,
  //DeleteFaq:`${baseUrl}/common/DeleteFaq`,

  //activity report api
  b2cActivityReport: `${baseUrl}/dashboard/report/b2cActivityReport`,
  b2bActivityReport: `${baseUrl}/dashboard/report/agentActivityReport`,
  transferProperty: `${baseUrl}/user/service/supplier/transfer`,
  cancelActivityBooking: `${B2C_URL}/webservice/activity/cancel`,
  b2cTransferReport: `${baseUrl}/dashboard/report/b2cTransferReport`,

  agentGroupList: `${baseUrl}/common/agentGroupList`,
  addAgentGroup: `${baseUrl}/user/service/addAgentGroup`,
  cancelHotelBooking: `${B2C_URL}/webservice/hotel/hotel/cancellation`,

  markupCountryList: `${baseUrl}/core/core-markup/countryList`,
  markupCityList: `${baseUrl}/core/core-markup/cityList`,
  transferVoucher: `${baseUrl}/dashboard/report/transferVoucher`,
  transferCancel: `${B2C_URL}/webservice/transfer/cancelBooking`,
  transferB2B: `${baseUrl}/dashboard/report/agentTransferReport`,
  activityVoucher: `${baseUrl}/dashboard/report/activityVoucher`,
  generateOTP: `${B2C_URL}/webservice/common/generateOTP`,
  // validateOTP:`${B2C_URL}/webservice/common/validateOTP`,
  validateOTP: `${baseUrl}/auth/service/validateOTP`,

  //AgentFaq
  addAgentFaq: `${baseUrl}/core/core-agent-login-alert/AddAgentFaq`,
  updateAgentFaq: `${baseUrl}/core/core-agent-login-alert/UpdateAgentFaq`,
  listAgentFaq: `${baseUrl}/core/core-agent-login-alert/ListAgentFaq`,
  deleteAgentFaq: `${baseUrl}/core/core-agent-login-alert/DeleteAgentFaq`,
  updateAgentFaqStatus: `${baseUrl}/core/core-agent-login-alert/UpdateAgentFaqStatus`,

  registerCountry: `${baseUrl}/dashboard/report/getCountryLists`,
  registerCity: `${B2B_URL}/b2b/common/getCityLists`,
  registerState: `${baseUrl}/common/getStatesLists`,
  WebTransferVoucher: `${B2C_URL}/webservice/transfer/voucher`,
  viewUser: `${baseUrl}/user/service/viewUser`,
  updateAgentGroup: `${baseUrl}/user/service/updateAgentGroup`,
  sendVerfication: `${baseUrl}/user/service/sendVerfication`,
  adHcnNumber: `${baseUrl}/dashboard/report/hcnNumber`,

  activityRefund: `${baseUrl}/sa/dashboard/report/activityRefund`,
  b2cBundleBookingReport: `${B2C_URL}/webservice/bundle-booking/bundleReport`,
  familyDeals: `${baseUrl}/hotel/hotels/familyDeals`,
  tourType: `${baseUrl}/tour/tours/tourType`,
  updateTourTypeStatus: `${baseUrl}/tour/tours/updateTourTypeStatus`,
  uploadTourTypeImage: `${baseUrl}/tour/tours/uploadTourTypeImage`,

  flightAd: `${baseUrl}/flight/flight-service/flightAd`,
  flightAdList: `${baseUrl}/flight/flight-service/flightAdList`,
  updateflightAdStatus: `${baseUrl}/flight/flight-service/updateflightAdStatus`,
  deleteFlightAd: `${baseUrl}/flight/flight-service/deleteFlightAd`,
  updateFlightAd: `${baseUrl}/flight/flight-service/updateFlightAd`,

  hotelEnquiryReport: `${baseUrl}/dashboard/report/hotelEnquiryReport`,
  hotelEnquiryStatusChange: `${baseUrl}/dashboard/report/hotelEnquiryStatusChange`,
  imageDownload: `${B2C_URL}/webservice/common/download`,
  addPartnerAirlines: `${baseUrl}/flight/flight-service/flightAirline`,
  getPartnerAirlines: `${baseUrl}/flight/flight-service/flightAirlineList`,
  updateAirlineStatus: `${baseUrl}/flight/flight-service/flightAirlineStatus`,
  deletePartnerAirlines: `${baseUrl}/flight/flight-service/deleteFlightAirline`,
  getAirlineImage: `${baseUrl}/flight/flight-service/getAirlineImage`,

  //Transfer CRS
  transferCreate: `${baseUrl}/transfer/create`,
  getVehicleList: `${baseUrl}/transfer/vechileList`,
  getVehiclePriceList: `${baseUrl}/transfer/vehiclePriceList`,
  addVehiclePrice: `${baseUrl}/transfer/addVehiclePrice`,
  updateVehiclePrice: `${baseUrl}/transfer/updateVehiclePrice`,
  updateTransfer: `${baseUrl}/transfer/update`,
  addTransferCity: `${baseUrl}/transfer/addTransferCity`,
  transferListDelete: `${baseUrl}/transfer/delete`,
  updateVehicleStatus: `${baseUrl}/transfer/updateVehicleStatus`,

  addVehicleType: `${baseUrl}/vehicle/vehicle-types/addVehicleType`,
  vehicleMasterList: `${baseUrl}/vehicle/vehicle-types/list`,
  vehicleMasterDelete: `${baseUrl}/vehicle/vehicle-types/delete`,
  vehicleMasterUpdate: `${baseUrl}/vehicle/vehicle-types/update`,

  vehicleMasterDataList: `${baseUrl}/transfer/vehicleMasterList`,
  createVehicleMaster: `${baseUrl}/transfer/createVehicle`,
  updateVehicleMaster: `${baseUrl}/transfer/updateVehicle`,
  deleteVehicleMaster: `${baseUrl}/transfer/deleteMaster`,
  updateVehicleMasterStatus: `${baseUrl}/transfer/updateVehicleMasterStatus`,

  transferCityList: `${B2C_URL}/webservice/transfer/crsCityList`,

  addTermsAndConditions: `${baseUrl}/car/updateTermsConditions`,
  getTermsConditions: `${baseUrl}/car/getTermsConditions`,
  addTransferImage: `${baseUrl}/transfer/uploadImage`,

  //Activity CRS
  addActivityType: `${baseUrl}/activity/activityType/addActivityType`,
  activityTypeList: `${baseUrl}/activity/activityType/activityTypeList`,
  updateActivityType: `${baseUrl}/activity/activityType/updateActivityType`,
  deleteActivityType: `${baseUrl}/activity/activityType/deleteActivity`,
  statusUpdateType: `${baseUrl}/activity/activityType/statusChangeActivity`,

  activityCountryList: `${baseUrl}/activity/activityCountry/activityCountryList`,
  addActivityCountry: `${baseUrl}/activity/activityCountry/addActivityCountry`,
  deleteActivityCountry: `${baseUrl}/activity/activityCountry/deleteActivityCountry`,
  editActivityCountry: `${baseUrl}/activity/activityCountry/editActivityCountry`,
  updateCountryStatus: `${baseUrl}/activity/activityCountry/statusChangeActivityCountry`,

  addActivityCity: `${baseUrl}/activity/activityCity/addActivityCity`,
  activityCityList: `${baseUrl}/activity/activityCity/activityCityList`,
  editActivityCity: `${baseUrl}/activity/activityCity/editActivityCity`,
  deleteActivityCity: `${baseUrl}/activity/activityCity/deleteActivityCity`,
  getAutoComplete: `${baseUrl}/activity/activityCity/autoComplete`,

  addActivityCRS: `${baseUrl}/activity-crs/addActivity`,
  addIncludesExcludes: `${baseUrl}/activity-crs/updateIncludesExcludes`,
  addTermsandConditions: `${baseUrl}/activity-crs/updateTermsConditions`,
  addSeasonPricing: `${baseUrl}/activity-crs/addActivityPricingDetails`,
  updateSeasonPricing: `${baseUrl}/activity-crs/updateActivityPricingDetails`,
  addChildPolicy: `${baseUrl}/activity-crs/addChildPolicy`,
  addBannerImage: `${baseUrl}/activity-crs/uploadBannerImage`,
  addGalleryImage: `${baseUrl}/activity-crs/uploadGallery`,
  getActivityCRSList: `${baseUrl}/activity-crs/activityList`,
  deleteActivity: `${baseUrl}/activity-crs/deleteActivity`,
  updateActivityStatus: `${baseUrl}/activity-crs/update-status`,
  updateGuideInd: `${B2C_URL}/webservice/activity/updateGuideInfo`,

  addActivityLanguage: `${baseUrl}/activity/activityLanguage/addActivityLanguage`,
  activityLanguageList: `${baseUrl}/activity/activityLanguage/activityLanguageList`,
  deleteActivityLanguage: `${baseUrl}/activity/activityLanguage/deleteActivityLanguage`,
  updateActivityLanguage: `${baseUrl}/activity/activityLanguage/updateActivityLanguage`,
  statusUpdateLanguage: `${baseUrl}/activity/activityLanguage/statusChangeActivityLanguage`,

  activityPricingDetailsList: `${baseUrl}/activity-crs/activityPricingDetailsList`,
  updateActivity: `${baseUrl}/activity-crs/updateActivity`,

  emailTourDetails: `${B2C_URL}/webservice/tour/emailTourDetails`,
  updateDriverInfo: `${B2C_URL}/webservice/transfer/updateDriverInfo`,

  updateAyurvedaCenter: `${baseUrl}/dashboard/report/updateAyurvedaCenter`,
  deleteAyurvedaCenter: `${baseUrl}/dashboard/report/deleteAyurvedaCenter`,
  addAyurvedaCenter: `${baseUrl}/dashboard/report/addAyurvedaCenter`,
  getAyurvedaCenters: `${baseUrl}/dashboard/report/listAyurvedaCenters`,
  addMeditationRetreat: `${baseUrl}/dashboard/report/addMeditationRetreat`,
  getMeditationRetreat: `${baseUrl}/dashboard/report/listMeditationRetreats`,
  updateMeditationRetreat: `${baseUrl}/dashboard/report/updateMeditationRetreat`,
  deleteMeditationRetreat: `${baseUrl}/dashboard/report/deleteMeditationRetreat`,

  //bus apis
  busReport: `${baseUrl}/dashboard/report/b2cBusReport`,
  createVendorMaster: `${baseUrl}/car/addVendor`,
  vendorList: `${baseUrl}/car/VendorList`,
  deleteVendor: `${baseUrl}/car/deleteVendor`,
  updateVendor: `${baseUrl}/car/updateVendor`,
  updateVendorStatus: `${baseUrl}/car/updateVendorStatus`,

  supervisionCityLists: `${baseUrl}/car/cityList`,
  supervisionCountryLists: `${baseUrl}/car/countryList`,

  addDriver: `${baseUrl}/car/addDriver`,
  driverList: `${baseUrl}/car/DriverList`,
  deleteDriver: `${baseUrl}/car/deleteDriver`,
  updateDriver: `${baseUrl}/car/updateDriver`,
  updateVehicle: `${baseUrl}/car/updateVehicleMasterStatus`,
  editDriverStatus: `${baseUrl}/car/editDriverStatus`,
  carAddPrice: `${baseUrl}/car/addPrice`,
  carEditPrice: `${baseUrl}/car/editPrice`,
  listPrice: `${baseUrl}/car/listPrice`,
  deletePrice: `${baseUrl}/car/deletePrice`,

  addVehicleMaster: `${baseUrl}/car/addVehicle`,
  deleteVehicleMasters: `${baseUrl}/car/deleteVehicle`,
  editVehicleMaster: `${baseUrl}/car/editVehicle`,
  listVehicleMaster: `${baseUrl}/car/listVehicle`,

  getVehicleType: `${baseUrl}/car/vehicleType`,

  addCarAmenities: `${baseUrl}/car/addCarAmenities`,
  updateCarAmenities: `${baseUrl}/car/updateCarAmenities`,
  deleteCarAmenities: `${baseUrl}/car/deleteCarAmenities`,
  listCarAmenities: `${baseUrl}/car/listCarAmenities`,
  editCarAmenitiesStatus: `${baseUrl}/car/editCarAmenitiesStatus`,

  tourUploadImage: `${baseUrl}/tour/tours/uploadItineraryimages`,
  saveDay: `${baseUrl}/tour/tours/addTourItineraries`,
  addItineraryActivities: `${baseUrl}/tour/tours/addItineraryActivities`,
  uploadVideo: `${baseUrl}/tour/tours/uploadBannerVideo`,
  addTourFaq: `${baseUrl}/tour/tours/addtourfaq`,
  createCarType: `${baseUrl}/car/AddVehicleType`,
  carTypeList: `${baseUrl}/car/GetVehicleTypeList`,
  deleteCarType: `${baseUrl}/car/deleteVehicleType`,
  updateCarType: `${baseUrl}/car/UpdateVehicleType`,
  updateStatusCarType: `${baseUrl}/car/UpdateVehicleTypeStatus`,

  addVehicleCombustion: `${baseUrl}/car/addVehicleCombustion`,
  VehicleCombustionList: `${baseUrl}/car/GetaddVehicleCombustionList`,
  deleteCombustionList: `${baseUrl}/car/deleteVehicleCombustion`,
  updateVehicleCombustion: `${baseUrl}/car/updateVehicleCombustion`,
  updateStatusVehicleCombustion: `${baseUrl}/car/updateVehicleCombustionStatus`,
  carManagementList: `${baseUrl}/dashboard/report/carMangement`,
  carReassign: `${baseUrl}/dashboard/report/carReassign`,
  carStatusChange: `${baseUrl}/dashboard/report/carMangementStatus`,
  guideList: `${baseUrl}/dashboard/report/guideRequestList`,
  updateGuideStatus: `${baseUrl}/dashboard/report/guideRequestStatus`,
  reviewList: `${baseUrl}/dashboard/report/guideReviewsList`,
  updateReviewStatus: `${baseUrl}/dashboard/report/guideReviewsStatus`,
  getGuideSections: `${baseUrl}/dashboard/report/listGuideMainContent`,
  addGuideSection: `${baseUrl}/dashboard/report/guideMainContent`,
  updateGuideSection: `${baseUrl}/dashboard/report/guideMainContent`,
  deleteGuideSection: `${baseUrl}/dashboard/report/deleteGuideMainContent`,
  guideProcessList: `${baseUrl}/dashboard/report/guideProcessList`,
  addGuideProcess: `${baseUrl}/dashboard/report/guideProcess`,
  updateGuideProcess: `${baseUrl}/dashboard/report/guideProcess`,
    deleteGuideProcess: `${baseUrl}/dashboard/report/deleteGuideProcess`,
    addAuthImage: `${baseUrl}/auth/service/uploadAuthImage`,
    addGuideLastSection: `${baseUrl}/dashboard/report/guidesideImage`,
      guideLastSectionList: `${baseUrl}/dashboard/report/listGuidesideImage`,
      updateGuideSectionStatus: `${baseUrl}/dashboard/report/editGuideMainStatus`,
      uploadWhyChooseImage: `${baseUrl}/common/uploadWhyChooseImage`,
      addwhyChooseusData: `${baseUrl}/common/addwhyChooseusData`,
      updateGuideProcessStatus: `${baseUrl}/dashboard/report/editGuideProcessStatus`,
      updateGuideLastStatus: `${baseUrl}/dashboard/report/editGuideSideMainStatus`,
      hotelHCNEmail: `${B2C_URL}/webservice/hotel/hotel/hotelHCNEmail`,
      ListServiceFaq: `${B2C_URL}/webservice/common/ListservicesFaq`,
      AddServiceFaq: `${baseUrl}/common/AddservicesFaq`,
            ListAboutFaq: `${B2C_URL}/webservice/common/ListAboutUsFaq`,
      AddAboutFaq: `${baseUrl}/common/AddAboutUsFaq`,
};
