import { environment } from '../../../environments/environment.prod';

const baseUrl = environment.SA_URL;
const API_URL = environment.B2C_URL;
const B2B_URL = environment.B2B_URL;
const proj1 = '/b2b';
const proj2 = '/supervision';

/* please maintain Ascending Order of the keys*/
export const apiMap = {
  agentDetails: `${baseUrl + proj1}/user/service/AgentDetails`,
  activate: `${B2B_URL + proj1}/user/service/activate`,
  bankDetails: `${baseUrl + proj1}/transaction/service/BankDetails`,
  bankAccountDetails: `${baseUrl + proj2}/cms/service/BankAccountDetails`,
  balanceManager: `${baseUrl + proj1}/transaction/service/BalanceManager`,
  banalanceTransferTypes: `${baseUrl + proj1}/transaction/service/BanalanceTransferTypes`,
  bookingCalender: `${baseUrl + proj1}/transaction/service/BookingCalender`,
  bookingDetails: `${baseUrl + proj1}/transaction/service/BookingDetails`,
  cabinClass: baseUrl + '/flight/service/CabinClass',
  changePassword: `${baseUrl + proj1}/user/service/ChangePassword`,
  creditLimitManager: `${baseUrl + proj1}/transaction/service/CreditLimitManager`,
  creditLimitRequest: `${baseUrl + proj1}/transaction/service/CreditLimitRequest`,
  dailySalesReport: `${baseUrl + proj1}/flight/service/DailySalesReport`,
  domainLogo: `${baseUrl + proj1}/user/service/DomainLogo`,
  uploadPassportVisa: `${baseUrl + proj1}/uploadPassportVisa`,
  editProfile: `${baseUrl + proj1}/user/service/EditProfile`,
  emailVoucher: `${baseUrl + proj1}/voucher/service/EmailVoucher`,
  extraServices: baseUrl + '/flight/service/ExtraServices',
  eventNotfications: `${baseUrl + proj1}/transaction/service/EventNotfications`,
  flightVoucher: `${baseUrl + proj1}/voucher/service/FlightVoucher`,
  latestTransactions: `${baseUrl + proj1}/transaction/service/LatestTransactions`,
  latestEventNotfications: `${baseUrl + proj1}/transaction/service/LatestEventNotfications`,
  moduleBookingCount: `${baseUrl + proj1}/transaction/service/ModuleBookingCount`,
  monthlyRecapReport: `${baseUrl + proj1}/transaction/service/MonthlyRecapReport`,
  registration: `${B2B_URL + proj1}/user/service/register`,
  supplier: `${B2B_URL + proj1}/user/service/supplier/create`,
  directorFormSubmit: `${B2B_URL + proj1}/user/service/directorFormSubmit`,
  setBalanceAlert: `${baseUrl + proj1}/transaction/service/SetBalanceAlert`,
  updateBalanceAlert: `${baseUrl + proj1}/transaction/service/UpdateBalanceAlert`,
  updateDomainLogo: `${baseUrl + proj1}/user/service/UpdateDomainLogo `,
  updateMarkup: `${baseUrl + proj1}/voucher/service/UpdateMarkup`,
  updateAgent: `${B2B_URL + proj1}/usermanagement/updateAgent`,
  userLogin: `${B2B_URL + proj1}/user/service/UserLogin`,
  updateProfile: `${baseUrl + proj1}/user/service/UpdateProfile`,
  userLogout: `${baseUrl + proj1}/user/service/UserLogout`,
  currencyList: `${baseUrl}/sa/flight/service/CurrencyList`,
  sendItinerary: `${API_URL}/webservice/flight/sendItinerary`,
  airportList: `${API_URL}/webservice/flight/autocomplete`,
  preferredAirlines: `${B2B_URL}/b2b/flight/service/preferredAirlines`,
  search: `${API_URL}/webservice/flight/search`,
  updateFareQuote: `${API_URL}/webservice/flight/fareQuote`,
  commitBooking: `${API_URL}/webservice/flight/commitBooking`,
  finalBooking: `${API_URL}/webservice/flight/reservation`,
  currencyConversionRate: `${API_URL}/webservice/flight/CurrencyConversionRate`,
  flightType: `${API_URL}/webservice/flight/flightType`,
  agentAccountLedger: `${B2B_URL}/b2b/reports/accountLedger`,
  transactionLogs: `${B2B_URL}/b2b/reports/transactionLogs`,
  balanceRequest: `${B2B_URL}/b2b/reports/balanceRequest`,
  agentActivate: `${B2B_URL}/b2b/user/service/activate`,
  refreshToken: `${baseUrl}/sa/auth/service/refreshToken`,
  countryList: `${baseUrl}/sa/common/CountryList`,
  fareRule: `${API_URL}/webservice/flight/fareRule`,
  markupReport: `${B2B_URL + proj1}/core/core-markup/markupList`,
  markupList: `${B2B_URL}/b2b/core/core-markup/markupList`,
  addMarkup: `${B2B_URL + proj1}/core/core-markup/addMarkup`,
  deleteMarkup: `${B2B_URL}/b2b/core/core-markup/deleteMarkup`,
  updateFlightMarkup: `${B2B_URL + proj1}/core/core-markup/updateMarkupList`,
  flightReports: `${B2B_URL + proj1}/reports/flightReport`,
  hotelReports: `${B2B_URL + proj1}/reports/hotelReport`,
  activityReports: `${B2B_URL + proj1}/reports/activityReport`,
  activityVouchers: `${B2B_URL + proj1}/activity/service/activityVoucher`,
  carReports: `${B2B_URL + proj1}/reports/carReport`,
  bookingReports: `${B2B_URL + proj1}/flight/service/BookingReports`,
  subAgentList: `${B2B_URL + proj1}/usermanagement/subAgentList`,
  userTitlelist: `${B2B_URL + proj1}/common/UserTitleList`,
  addSubAgent: `${B2B_URL + proj1}/usermanagement/addSubAgent`,
  updateSubAgent: `${B2B_URL + proj1}/usermanagement/updateSubAgent`,
  travellerManagementList: `${B2B_URL + proj1}/travellerManagement/travellerManagementList`,
  addTravellerManagement: `${B2B_URL + proj1}/travellermanagement/addTravellerManagement`,
  updateTravellerManagement: `${B2B_URL + proj1}/travellermanagement/updateTravellerManagement`,
  autoCompleteEmail: `${B2B_URL + proj1}/travellermanagement/autoComplete`,
  getAgentLoginAlert: `${baseUrl}/sa/core/core-agent-login-alert/getAgentLoginAlert`,
  addCoreHelpdesk: `${B2B_URL + proj1}/core/core-helpdesks/addCoreHelpdesk`,
  coreHelpdeskList: `${B2B_URL + proj1}/core/core-helpdesks/coreHelpdeskList`,
  updateLogouttime: `${B2B_URL + proj1}/user/service/updateLogoutDateTime`,
  staticPageContentsList: `${B2B_URL + proj1}/common/staticPageContentsList`,
  sliderSettingsList: `${B2B_URL + proj1}/common/sliderSettingsList`,
  agentSubAgentFlightCounts: `${B2B_URL + proj1}/common/bookings/agentSubAgentFlightCounts`,
  agentSubAgentHotelCounts: `${B2B_URL + proj1}/common/bookings/agentSubAgentHotelCounts`,
  agentSubAgentCarCounts: `${B2B_URL + proj1}/common/bookings/agentSubAgentCarCounts`,
  getAgentSubAgentTotalLoginDetails: `${B2B_URL + proj1}/common/bookings/getAgentSubAgentTotalLoginDetails`,
  uploadUserProfilePhoto: `${B2B_URL + proj1}/usermanagement/uploadUserProfilePhoto`,
  updateLostBaggageProtectionPrice: `${API_URL}/webservice/flight/updateLostBaggageProtectionPrice`,
  baggageproductList: `${B2B_URL}/b2b/baggageInsurance/productList`,
  pnrRetrieve: `${API_URL}/webservice/flight/pnrRetrieve`,
  checkWalletBalance: `${B2B_URL}/b2b/account-system/checkWalletBalance`,
  deductFromWallet: `${B2B_URL}/b2b/account-system/deductFromWallet`,
  cancelFlightBooking: `${API_URL}/webservice/flight/cancellation`, //Added by Asha Swamy 17-09-2021
  cancelHotelBooking: `${API_URL}/webservice/hotel/hotel/cancellation`,
  voidFlightBooking: `${API_URL}/webservice/flight/void`, //Added by Asha Swamy 25-01-2022
  transactionLogsAccountSys: `${B2B_URL}/b2b/account-system/transactionLogs`,
  setBalanceAlertAccountSys: `${B2B_URL}/b2b/account-system/setBalanceAlert`,
  updateBalanceAlertAccountSys: `${B2B_URL}/b2b/account-system/updateBalanceAlert`,
  accountLedgerAccountSys: `${B2B_URL}/b2b/account-system/accountLedger`,
  balanceRequestAccountSys: `${B2B_URL}/b2b/account-system/balanceRequest`,
  balanceRequestListAccountSys: `${B2B_URL}/b2b/account-system/balanceRequestList`,
  creditLimitRequestAccountSys: `${B2B_URL}/b2b/account-system/creditLimitRequest`,
  creditLimitRequestListAccountSys: `${B2B_URL}/b2b/account-system/creditLimitRequestList`,
  listBankAccountAccountSys: `${B2B_URL}/b2b/cms/cms-bankaccounts/listBankAccount`,
  getAgentById: `${B2B_URL}/b2b/usermanagement/getAgentById`,
  commissionList: `${B2B_URL}/b2b/core/core-commission/commissionList`,
  getRequestTypes: `${B2B_URL}/b2b/common/getRequestTypes`,
  getModuleTypes: `${B2B_URL}/b2b/common/getModuleTypes`,
  phoneCodeList: `${B2B_URL}/b2b/common/phoneCodeList`,
  getPaymentModes: `${B2B_URL}/b2b/common/getPaymentModes`,
  getDomainLogo: `${B2B_URL}/b2b/common/uploadDomainLogo`,
  cityList: `${API_URL}/webservice/hotel/hotel/autoCompleteSmyrooms`,
  searchHotel: `${API_URL}/webservice/hotel/hotel/searchHotels`,
  hotelDetails: `${API_URL}/webservice/hotel/hotel/hotelDetails`,
  blockRoom: `${API_URL}/webservice/hotel/hotel/blockRooms`,
  addPaxDetails: `${API_URL}/webservice/hotel/hotel/addPaxDetails`,
  reservation: `${API_URL}/webservice/hotel/hotel/reservation`,
  hotelVoucher: `${API_URL}/webservice/hotel/hotel/voucher`,
  b2bHotelVouher: `${B2B_URL}/b2b/hotel/service/hotelVoucher`,
  servicePurchase: `${B2B_URL}/b2b/baggageInsurance/servicePurchase`,
  listFlightTopDestination: `${B2B_URL}/b2b/flight/service/listFlightTopDestination`,
  ManageDomain: `${B2B_URL}/b2b/common/ManageDomain`,
  executePayment: `${B2B_URL}/b2b/paymentGateway/executePayment`,
  executePayment_local: `http://localhost:4008/b2b/paymentGateway/executePayment`,
  b2bFlightVoucher: `${B2B_URL}/b2b/flight/service/flightVoucher`,
  completeBooking: `${API_URL}/webservice/hotel/hotel/completeBooking`,
  completeBooking_dev: `http://localhost:4005/webservice/hotel/hotel/completeBooking`,
  searchByBookindId: `${B2B_URL}/b2b/common/bookings/searchByBookindId`,
  forgotPassword: `${B2B_URL}/b2b/user/service/forgotPassword`,
  updatePassword: `${B2B_URL}/b2b/user/service/updatePassword`,
  resetPassword: `${B2B_URL}/b2b/user/service/resetPassword`,
  notifications: `${B2B_URL}/b2b/logger/service/notifications`,
  activeNotificationCount: `${B2B_URL}/b2b/logger/service/activeNotificationCount`,
  updateViewedNotifications: `${B2B_URL}/b2b/logger/service/updateViewedNotifications`,
  paymentConfirmation: `${B2B_URL}/b2b/flight/service/paymentConfirmation`,
  flightUpdatePNR: `${B2B_URL}/b2b/reports/flightUpdatePNR`,
  reservationResponse: `${API_URL}/webservice/flight/reservationResponse`,
  createAppReference: `${API_URL}/webservice/common/createAppReference`,
  getPrivilegePageList: `${B2B_URL}/b2b/core/core-privilege/getPrivilegePageList`,
  getPrivilegedUser: `${B2B_URL}/b2b/core/core-privilege/getPrivilegedUser`,
  updatePrivilegeAccess: `${B2B_URL}/b2b/core/core-privilege/updatePrivilegeAccess`,
  setUserPrivilege: `${B2B_URL}/b2b/core/core-privilege/setUserPrivilege`,
  verifyOtp: `${B2B_URL}/b2b/user/service/verifyOtp`,
  revokeParticularPrivilege: `${B2B_URL}/b2b/core/core-privilege/revokeParticularPrivilege`,
  instantRecharge: `${B2B_URL}/b2b/paymentGateway/instantRecharge`,
  sslTransactionInit: `${B2B_URL}/b2b/paymentGateway/sslTransactionInit`,
  activeAirlineHotelPartnersList: `${B2B_URL}/b2b/core/core-airline-hotel-partners/activeAirlineHotelPartnersList`,
  hotelPaymentConfirmation: `${B2B_URL}/b2b/hotel/service/paymentConfirmation`,
  liveFlightInfo: `${B2B_URL}/b2b/flight/service/liveFlightInfo`,
  flightInfo: `${B2B_URL}/b2b/flight/service/flightInfo`,
  flightInvoiceReport: `${B2B_URL + proj1}/reports/flightInvoiceReport`,
  sendInvoice: `${B2B_URL + proj1}/reports/sendInvoice`,
  getPaymentGateWays: `${API_URL}/webservice/paymentGateway/getPaymentGateWays`,
  uploadFlightDocument:`${API_URL}/webservice/flight/documentUpload`,
  importPnr: `${API_URL}/webservice/flight/importPNR`,
  updateWallet:`${B2B_URL}/b2b/account-system/updateWallet`,
  flightSeatAvailability: `${API_URL}/webservice/flight/seatAvailability`,
  // agentAccountLedger: `${baseUrl + proj1}/transaction/service/AgentAccountLedger`,
  // airportList: `http://Booking 247.com:4005/webservice/flight/autocomplete`,
  // balanceRequest: `${baseUrl + proj1}/transaction/service/BalanceRequest`,
  // bookingReports: `${baseUrl + proj1}/flight/service/BookingReports`,
  // bookingReports:`http://Booking 247.com/antrip_webservices/b2b/flight/service/BookingReports`,
  // commitBooking: baseUrl + '/flight/service/CommitBooking',
  // countryList: baseUrl + '/supervision/common/service/CountryList',
  // recentSearchHistory: `${baseUrl}/flight/service/RecentSearchHistory`,
  // updateFlightMarkup: `${B2B_URL + proj1}/core/core-markup/updateMarkup`,
  // userTitlelist:`${baseUrl }/sa/user/service/userTitleList`,
  // preferredAirlines: `${baseUrl }/sa/flight/flight-service/preferredAirlines`,

  //Activity api's
  availability:`${API_URL}/webservice/activity/search`,
  activityCityList: `${API_URL}/webservice/activity/cityList`,
  activityTripList: `${API_URL}/webservice/activity/tripList`,
  activityProductDetails: `${API_URL}/webservice/activity/ProductDetails`,
  activityBlockTrip: `${API_URL}/webservice/activity/blocktrip`,
  activityAddPax: `${API_URL}/webservice/activity/addPax`,
  activityConfirm: `${API_URL}/webservice/activity/confirmBooking`,
  activityVoucher: `${API_URL}/webservice/activity/voucher`,
  listPromocode: `${API_URL}/webservice/common/listPromocode`,
  userTravellersList: `${API_URL}/webservice/user/userTravellersList`,
  tourAutocompleteCity: `${API_URL}/webservice/tour/autoComplete`,
  searchTour: `${API_URL}/webservice/tour/search`,
  tourDetail: `${API_URL}/webservice/tour/tourDetail`,
  homeTourData: `${API_URL}/webservice/tour/homePublishsearch`,
  tourValuation: `${API_URL}/webservice/tour/tourValuation`,
  b2bTourInquiryReport: `${B2B_URL}/b2b/reports/tourInquiryReport`,
  sendEnquiry: `${API_URL}/webservice/tour/sendEnquiry`,
  createAppRef: `${API_URL}/webservice/common/createAppReference`,
  tourAddPax: `${API_URL}/webservice/tour/addPaxDetails`, 
  tourConfirm: `${API_URL}/webservice/tour/confirmBooking`,
  tourVoucher: `${API_URL}/webservice/tour/Voucher`,
  b2bTourEnquiryList: `${baseUrl}/dashboard/report/tourInquiryReport`,
  tourB2bReport: `${B2B_URL}/b2b/reports/tourReport`,
  b2cTourEnquiryStatusChange: `${baseUrl}/dashboard/report/b2cTourEnquiryStatusChange`,
  b2bTourVoucher: `${API_URL}/webservice/tour/Voucher`,
  homeTourDataList: `${baseUrl}/tour/tours/toursList`,
  tourCountryList: `${API_URL}/webservice/tour/countryList`,
  tourPackageDetail: `${baseUrl}/tour/PackageMasterList/PackageMasterList`,
  getPackageIncludeList: `${baseUrl}/tour/includes_master/IncludeMasterList`,

  //Transfer api's
  transferCityList: `${API_URL}/webservice/transfer/cityList`,
  transferSearch: `${API_URL}/webservice/transfer/availability`,
  productDetails: `${API_URL}/webservice/transfer/productDetails`,
  tripList: `${API_URL}/webservice/transfer/tripList`,
  blocktrip: `${API_URL}/webservice/transfer/blocktrip`,
  transferAddPax: `${API_URL}/webservice/transfer/addPax`,
  transferConfirm: `${API_URL}/webservice/transfer/confirmBooking`,
  transferVoucher: `${API_URL}/webservice/transfer/voucher`,
  transferCancel: `${API_URL}/webservice/transfer/CancelBooking`,
  getPromoCodeInfo:`${API_URL}/webservice/common/getPromoCodeInfo`,
  transferReport:`${B2B_URL}/b2b/reports/transferReport`,
  cancelActivityBooking:`${API_URL}/webservice/activity/cancel`,

  //register api's
  hotelCurrencyConverison: `${baseUrl}/sa/cms/service/CurrencyConversion`,
  userTitleList: `${API_URL}/webservice/common/titleList`,
  commonCityList: `${baseUrl}/sa/common/city/findAllCities`,

  listAgentFaq: `${baseUrl}/sa/core/core-agent-login-alert/ListAgentFaq`,
  registerCountry: `${B2B_URL}/b2b/common/getCountryLists`,
  registerCity: `${B2B_URL}/b2b/common/getCityLists`,
  registerState: `${B2B_URL}/b2b/common/getStatesLists`,
  getReceiverList: `${B2B_URL}/b2b/account-system/agentActiveLists`,
  initiatePayment: `${B2B_URL}/b2b/paymentGateway/barclayardB2BTransactionInit`,
  initiatePaymentReport: `${B2B_URL}/b2b/paymentGateway/barclayardB2BReportTransactionInit`,
  paymentConfirm: `${B2B_URL}/b2b/paymentGateway/barclayardTransactionStatus`,

//cart
addBundleBooking: `${API_URL}/webservice/bundle-booking/addBundleBooking`,
getBundleBooking : `${API_URL}/webservice/bundle-booking/getBundleBooking`,
removeBundleBooking: `${API_URL}/webservice/bundle-booking/removeBundleBooking`,
commitBundleBooking: `${API_URL}/webservice/bundle-booking/addPaxDetails`,
finalBundleBooking: `${API_URL}/webservice/bundle-booking/reservation`,
bundleVoucher: `${API_URL}/webservice/bundle-booking/bundleVoucher`,
cartSearchInfo:`${API_URL}/webservice/common/searchInfo`,

//B2c Supplier
hotelTypeList: `${baseUrl}/sa/hotel/hotel-types/hotelTypeList`,
getCity:`${baseUrl}/sa/common/city/findAll`,
addSupplier:`${API_URL}/webservice/supplier/create`,
mealList:`${API_URL}/webservice/common/meals/findAll`,
weekList:`${API_URL}/webservice/common/weekend/findAll`,
viewList:`${API_URL}/webservice/common/views/findAll`,
supplierCountryList:`${API_URL}/webservice/common/country/findAll`,
supplierCityList:`${API_URL}/webservice/common/city/findAll`,
hotelType:`${API_URL}/webservice/common/hotelType/findAll`,
currencyConverison: `${baseUrl}/sa/cms/service/CurrencyConversion`,
//contact Us
AddContactList:`${API_URL}/webservice/common/AddContactList`,

//OTP
generateOTP:`${API_URL}/webservice/common/generateOTP`,
validateOTP:`${API_URL}/webservice/common/validateOTP`,

//login
validateOTPLogin:`${API_URL}/webservice/auth/verifyOtp`,

bundleBookingReport: `${API_URL}/webservice/bundle-booking/bundleReport`,

hotelEmail: `${API_URL}/webservice/hotel/hotel/hotelEmail`,
flightEmail: `${API_URL}/webservice/flight/flightEmail`,
activityEmail: `${API_URL}/webservice/activity/activityEmail`,
transferEmail: `${API_URL}/webservice/transfer/transferEmail`,
emailTourDetails: `${API_URL}/webservice/tour/emailTourDetails`,

//Tour Radar
getAccommadationDetails: `${API_URL}/webservice/tour/accommadation`,
tourEvaluation: `${API_URL}/webservice/tour/tourValuation`,
imageDownload: `${API_URL}/webservice/common/download`,
ticketingRequest: `${B2B_URL}/b2b/flight/service/ticketingRequest`,
getpaymentCharges: `${API_URL}/webservice/common/getpaymentCharges`,
updatePaymentCharges: `${API_URL}/webservice/common/updatePaymentCharges`,
getPaymentCharges: `${API_URL}/webservice/common/getpaymentCharges`,
removePaymentCharges: `${API_URL}/webservice/common/removePaymentCharges`,
updateDriverInfo: `${API_URL}/webservice/transfer/updateDriverInfo`,
cancelTour:  `${API_URL}/webservice/tour/cancelBooking`,
};
